# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contact_tracing.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contact_tracing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ontact_tracing.proto\x12\x0f\x63ontact_tracing\"C\n\x17OutbreakLocationRequest\x12\x15\n\rlocation_name\x18\x01 \x01(\t\x12\x11\n\ttest_type\x18\x02 \x01(\t\"<\n\x18OutbreakLocationResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08user_ids\x18\x02 \x03(\t2\x84\x01\n\x15\x43ontactTracingService\x12k\n\x14SendOutbreakLocation\x12(.contact_tracing.OutbreakLocationRequest\x1a).contact_tracing.OutbreakLocationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contact_tracing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OUTBREAKLOCATIONREQUEST']._serialized_start=42
  _globals['_OUTBREAKLOCATIONREQUEST']._serialized_end=109
  _globals['_OUTBREAKLOCATIONRESPONSE']._serialized_start=111
  _globals['_OUTBREAKLOCATIONRESPONSE']._serialized_end=171
  _globals['_CONTACTTRACINGSERVICE']._serialized_start=174
  _globals['_CONTACTTRACINGSERVICE']._serialized_end=306
# @@protoc_insertion_point(module_scope)
