apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose-windows-amd64.exe convert --controller deployment
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: contact-tracing-service
  name: contact-tracing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: contact-tracing-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Kompose\kompose-windows-amd64.exe convert --controller deployment
        kompose.version: 1.35.0 (9532ceef3)
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8009"
      labels:
        io.kompose.service: contact-tracing-service
    spec:
      containers:
        - env:
            - name: CONTACT_TRACING_GRPC
              value: contact_tracing_service:50051
            - name: KAFKA_BROKER
              value: kafka:9092
          image: bsekar24/distributedsystems2-contact-tracing-service:latest 
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - nc -z kafka 9092
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          name: contact-tracing-service
          ports:
            - containerPort: 50051
              protocol: TCP
            - containerPort: 8009  # Added Prometheus metrics port
              protocol: TCP
      restartPolicy: Always
