apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose-windows-amd64.exe convert --controller deployment
    kompose.version: 1.35.0 (9532ceef3)
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8009"
  labels:
    io.kompose.service: contact-tracing-service
  name: contact-tracing-service
spec:
  type: ClusterIP
  ports:
    - name: "grpc"
      port: 50051
      targetPort: 50051
    - name: "metrics"
      port: 8009
      protocol: TCP
      targetPort: 8009
  selector:
    io.kompose.service: contact-tracing-service
