apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose-windows-amd64.exe convert --controller deployment
    kompose.version: 1.35.0 (9532ceef3)
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8001"
  labels:
    io.kompose.service: database-service
  name: database-service
spec:
  type: ClusterIP
  ports:
    - name: "metrics"
      port: 8001
      targetPort: 8001
  selector:
    io.kompose.service: database-service
