apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose-windows-amd64.exe convert --controller deployment
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: database-service
  name: database-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Kompose\kompose-windows-amd64.exe convert --controller deployment
        kompose.version: 1.35.0 (9532ceef3)
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8001"
      labels:
        io.kompose.service: database-service
    spec:
      containers:
        - image: bsekar24/distributedsystems2-database-service:latest
          imagePullPolicy: Always
          name: database-service
          ports:
            - containerPort: 8001
              protocol: TCP
      restartPolicy: Always
