apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose-windows-amd64.exe convert --controller deployment
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: kafka-init
  name: kafka-init
spec:
  ports:
    - name: "8007"
      port: 8007
      targetPort: 8007
  selector:
    io.kompose.service: kafka-init
