apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notification-service
  namespace: monitoring-distributedsystems 
  labels:
    release: monitoring-stack  # Ensure this matches your Prometheus instance's label selector
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      io.kompose.service: notification-service
  endpoints:
    - port: "metrics"
      path: "/metrics"
      interval: 15s  # Scrape metrics every 15 seconds
      scheme: "http"