apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose-windows-amd64.exe convert --controller deployment
    kompose.version: 1.35.0 (9532ceef3)
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8006"
  labels:
    io.kompose.service: notification-service
  name: notification-service
spec:
  type: ClusterIP
  ports:
    - name: "metrics"
      port: 8006
      protocol: TCP
      targetPort: 8006
  selector:
    io.kompose.service: notification-service
