apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose-windows-amd64.exe convert --controller deployment
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: preprocessing-service
  name: preprocessing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: preprocessing-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Kompose\kompose-windows-amd64.exe convert --controller deployment
        kompose.version: 1.35.0 (9532ceef3)
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8002"
      labels:
        io.kompose.service: preprocessing-service
    spec:
      containers:
        - env:
            - name: API_URL
              value: http://database-service:8001/api/v1/data
            - name: KAFKA_BROKER
              value: kafka:9092
          image: bsekar24/distributedsystems2-preprocessing-service:latest
          imagePullPolicy: Always
          name: preprocessing-service
          ports:
            - containerPort: 8002
              protocol: TCP
      restartPolicy: Always
