apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: preprocessing-service
  namespace: monitoring-distributedsystems
  labels:
    release: monitoring-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      io.kompose.service: preprocessing-service
  endpoints:
    - port: metrics
      path: /metrics
      interval: 10s
      scheme: "http"