apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose-windows-amd64.exe convert --controller deployment
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: realtime-data-service
  name: realtime-data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: realtime-data-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Kompose\kompose-windows-amd64.exe convert --controller deployment
        kompose.version: 1.35.0 (9532ceef3)
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8003"
      labels:
        io.kompose.service: realtime-data-service
    spec:
      containers:
        - env:
            - name: API_URL
              value: http://preprocessing-service:8002/process
          image: bsekar24/distributedsystems2-realtime-data-service:latest
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - curl -f http://preprocessing-service:8002/health || exit 1
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          name: realtime-data-service
          ports:
            - containerPort: 8003
              protocol: TCP
      restartPolicy: Always
