apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose-windows-amd64.exe convert --controller deployment
    kompose.version: 1.35.0 (9532ceef3)
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8003"
  labels:
    io.kompose.service: realtime-data-service
  name: realtime-data-service
spec:
  type: ClusterIP
  ports:
    - name: "metrics"
      port: 8003
      protocol: TCP
      targetPort: 8003
  selector:
    io.kompose.service: realtime-data-service
